"""auto-vote

Revision ID: a17f74ca60ea
Revises: df436be93fc0
Create Date: 2026-06-04 15:58:52.723548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a17f74ca60ea'
down_revision: Union[str, Sequence[str], None] = 'df436be93fc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'post_id')
    )
    # op.add_column('posts', sa.Column('creator_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    # op.create_index(op.f('ix_posts_content'), 'posts', ['content'], unique=False)
    # op.create_index(op.f('ix_posts_id'), 'posts', ['id'], unique=False)
    # op.create_index(op.f('ix_posts_title'), 'posts', ['title'], unique=False)
    # op.drop_column('posts', 'created_at')
    # op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    # op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f('ix_users_id'), table_name='users')
    # op.drop_index(op.f('ix_users_email'), table_name='users')
    # op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    # op.add_column('posts', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    # op.drop_index(op.f('ix_posts_title'), table_name='posts')
    # op.drop_index(op.f('ix_posts_id'), table_name='posts')
    # op.drop_index(op.f('ix_posts_content'), table_name='posts')
    # op.drop_column('posts', 'creator_at')
    op.drop_table('votes')
    # ### end Alembic commands ###
